/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/scene.gltf 
Author: scailman (https://sketchfab.com/scailman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-plane-76230052903540e9aeb46b7db35329e4
Title: Low Poly Plane
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.186, -3.36]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Elevator_Plane_0.geometry} material={materials.Plane} position={[1.137, -0.32, -0.05]} />
      </group>
      <group position={[0, -0.194, 4.137]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Propeller_Plane_0.geometry} material={materials.Plane} position={[0, -1.327, 0.02]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0, 0.583, -3.429]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Rudder_Plane_0.geometry} material={materials.Plane} position={[0, -3.429, -1.002]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[4.117, 0.617, 0.956]} rotation={[-Math.PI / 2, 0, -0.175]}>
        <mesh geometry={nodes.LeftAileron_Plane_0.geometry} material={materials.Plane} position={[-4.22, 0.227, -1.035]} rotation={[Math.PI / 2, 0.175, 0]} />
      </group>
      <group position={[-4.228, 0.617, 0.947]} rotation={[-Math.PI / 2, 0, 0.175]}>
        <mesh geometry={nodes.RightAileron_Plane_0.geometry} material={materials.Plane} position={[4.329, 0.199, -1.036]} rotation={[Math.PI / 2, -0.175, 0]} />
      </group>
      <group position={[0, -0.186, -2.924]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Stabilizer_Plane_0.geometry} material={materials.Plane} position={[1.137, 0.115, -0.05]} />
      </group>
      <group position={[-1.838, 0.599, 0.762]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.RightFlap_Plane_0.geometry} material={materials.Plane} position={[1.838, 0.762, -1.017]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0, -1.22, 3.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.FrontWheel_Plane_0.geometry} material={materials.Plane} position={[0.022, 0, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
      <group position={[-1.227, -1.22, 1.367]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.RightWheel_Plane_0.geometry} material={materials.Plane} position={[0.022, 0, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
      <group position={[1.227, -1.22, 1.367]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LeftWheel_Plane_0.geometry} material={materials.Plane} position={[0.022, 0, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
      <group position={[1.756, 0.599, 0.762]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LeftFlap_Plane_0.geometry} material={materials.Plane} position={[-1.756, 0.762, -1.017]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-0.041, -0.013, 0.104]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Body_Plane_0.geometry} material={materials.Plane} position={[0.041, 0.104, -0.406]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
