
# Crews
CREW_NUMBER = 10 #def 100

# Airplane 
NUM_AIRPLANES = 10 #def 100

# Flights
NUM_DAYS = 7
NUM_FLIGHTS_PER_DAY = 100 #def 5

# FlightCrews
CREW_PER_FLIGHT = 5 #def 5

# PASSENGERS PER FLIGHT
PASSENGERS_PER_FLIGHT = 10 #def 10

# USERS
USERS_TO_GENERATE = 10