# Generated by Django 4.2.7 on 2023-11-29 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="available",
        ),
    ]
