# Generated by Django 4.2.7 on 2023-12-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_promotion_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
